spring:
  application:
    name: WealthFlow

  datasource:
    url: jdbc:sqlite:wealthflow.db
    driver-class-name: org.sqlite.JDBC

  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.jack.wealthflow.model
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true